on:
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: donevgoran/ubuntu-cicd
    steps:
    - run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEAzHuJMCktYKRmJYnyGaW2c1assQA+JOz4kLttXTMXS90KFlu8
eH4BHObj0CXslJ1SLuqUWqGzWyc7MZOqF1mmLlQGIREvACD6LjWbHhe6XL0/FyJq
DfBYKLX0t0rgZ8e+bcbi0P67dhIbAnWl0uM4hHkK2wx7FIPqnd30pA0lGz1MlnpC
J5PpwhAbLxUvq1LsfW8sww/lPPMQE40Z9PoP4iX5pAaz0MhnrPwOjZhxLOC1i4Bb
UqhW3QUJcfSUUMLh3am0/EP4vkg3gfl7xM6W2A5oft+bKnu7QVVi2DOg+nPFVvsc
1PuvOp8pcW2cgUdxfk4gdWgWwf4v+gjFpDrPvjVroLS+5anzz6C+kG4pATJ10sAD
5B1/O2VPFCMw5rGPne8WXuR8fniiqy+bo2LevNh26OIMOxAQt9ecVOLwtALpbvMx
l5lIJFnVxwhPFaFPagOshIio8o2Fh+GaOvX4sycKzcMjRcRGQqtlafPdY5cJP9rM
cT5Wx7jNWPJQuHE1yEUKbqOm6YVWWINcXiiebCGU9lRJnf6UYnSaib1ucxNy+BJL
JNGHsBxYEUt4xAP2GXSTDANpO2pbPRYiOk/y1DZ7E425k+CyL8GkT8YAxf9qiRJy
ZZncK9P+Ks8flWIX35PsjZVlgpRnHrUp+gxDbQdu7KIKNkjSWWuWVg4ay9MCAwEA
AQKCAgAK5To2GruUPq5CqcsAmtfR5XhmJgEprobAD3yQTrybCjgTYOf186DTjWnu
GVc1w/wxC8bD3YHVBY4d4iRaAijcpxV8hZHfi+JIvAp72//OGTdXYDoObBQGd0uG
yLKUVQxMhSBoymnqrKRLyUEAr6K/TEPL0CpuuWiy6LS0WQ71GJsQGYuU2EjIUltg
ctyLYGvBcz8LVbl9OeZNZGNRrlFSV3upxcGnCkab7QJJgSnmnkKOIFS9XsLiG/aY
39NXSksGqJhAKM8ENIzgnA6AOhHHiV0ABaIa7WTY4lfV9UpKjgihzdeHcbGwifKH
XLPOH6Roenk4SEeOJqEfzX/adFfFTmkcUCggdh+fjSZbl7xUOFUi9lfAlj7vVcb1
qa6AHLYAv8D463Dx+P+J2vvNkuK4ZJELXMxMCiGr9yEboBGBF7Z7EGTmZPV1W+Hw
NxEMj2kDNR6ht158v7RL80LrtHkzdVcMebdvSciJUYHCZKHx7YAutxyxvGQ7TcsN
SxCD/NU64ZF1y/Qd1oa948FQXIBuH15ANDgFlm6uJJXBLd0+cvlCIFsVIMfjNcOm
b8dSIDbXeh9CEiHmHKTJB7FdekeEt/bjv8uYAkXzrPZUsOiM10XVsX6FM58w/MQx
BP0ekmeLpHpFNk7Nk35nAtiL+kN3IEbikquLknLiQnW9TLMpgQKCAQEA54L5T7Zx
lLvlCMOzZaIf6sRFhr7PNX9LfXXd5qMn2vFkNj/D6IO0uoNVlVl7L9DvBv0oPU+3
FUHT7gKKm9R1yuCQspnrDQMUre6DhVBZlmF6j/g0+9NgfIzO7g5mOPYnZjrSVkEi
ueWnSLK7th9HkaMzlJeYFLaftlYdJkIDGCaA8+Go3skhcaic3RUhPsITgnBYMJPf
RvEW/VxQbcH77o7hX7WnIC7tf0gJ3Gbb0o8TiSoUQxNN6PaTV7u52F1hjb1+fkJN
jbi8W0K++du2KdIu9BBaKkI/E2vr0H0JEgneVgcdWNCgPvhuH3nvRey6+fEkc+pO
7+BmZunmSdcjsQKCAQEA4hymtxvDF9n0zOquQSDVy42I3P4yFXy+AJsV7tUqOP4C
K6mwp2GqOSxSMSgEhSPZmaeA3/8FHwtwBfds8NCAZvwOIhkVGVRu4HH1up5JDutl
w+rwZKUtUt/Sfus12IIcbaQn8SRV+azqaTeGxX0dhyZmDtO5HqGlE00S4Z/uuXJq
TQdjuP8Ua1C+sS/FI0cv4Dcfkj7ZhAH4PTBP6zUX0xkVsxTxPXEZldCskiFPJ6eP
FgXWg1f2aNd9uPJK1HfnaEGP4ON+yGusEz8imCZmWofcEu5PT5vuztqLvMrBIZE6
IQSxACw0kPZG7RspW+7JPNlbkRXE5FkeUcvUwZdcwwKCAQEAzmUy1UEG852rq+uk
9TfbkpZWkbFs0/nfmENLiEHu1z+bos2oX5ODvUA3PYXf0BpJ7wYlKLv3sijUwv1b
C2AXf75C4idcqWYUupfIg0LGC85t0QpsWhHxlDiIhy0pLyEssPRB7wn05px6TdKi
jNRIHuvLoW6g8954drtBE4mIbrBtCIAm6C+R9F1pM6SR1fx6HjEAPpamWP25DDmP
rrphWyXggU5WZ9fOfkoAGJFO6uIJfaCZHc+JBudFJtNC9UUTIqVMr013DKEks4vG
7MRXG+O5XndxmvkieLMfMek2+/D2WeXP4Q1lv54Ft2Qi0EkjzI6SfBDpPOvm/1sJ
psz5kQKCAQEAyhJC57eW1dUCUrOUwT2f84bsfltp1QwjHZV7t3KnhkFzHSRMbHn6
z5eNaMLTr0zHpestYIGfSQxGs/5YTKp5Zg/ybYSu93EemdUefwYAUqYKz1lCNx/q
7np6utRnzbMRxuaCj54ie7yNzTRDbHERF3w4jx2l/fsF9MbXje4JQZA/8dEdzPGh
hPqnQOBpNMrkvWNmAqPKbo/4Em7/rTtIrG5plx6rLXbLH7la0EmWXOEBHfRfrgfJ
fg6/G67lMxZpJyIYfCmzX1fic1zkBMekh1mNUxnIpWO8uv5TDYjBqscIBQQVTwsy
ey6tWi8A+ljfXVL+4x1qVYxTbVRVMiGcUwKCAQEAmRVx/ZiPTelK8rbZZO7lAoTB
M8dEbcKTcUkj3xsoxuuisPIOaLBW3CcLjhdOhd8uBy7w7PmrpK3ZtrwP6zcDnNJo
DUEhmZ/XvoqQsOiLrbFcHy9/AZKL0P6ulENP5Dsh09xRry4o1upBRgaNR7W5wKPT
szcYdEQhZz6YBL8JJ3lu0y+WFS1OWl1xSWjMVTlgZwgylCyIRGfZPqihc9OwGCcl
FkUbB++WPMdyJfJ/kH9DX6caacRT/kHKaa0RKDmYeiF+7eP/eJshLcieDjx8dQcV
eh3D06QICGabXLYgX2FbrN0ldqrYITsvIyqQj6hPBhZLY2c2EHMhjLadpVbNyQ==
-----END RSA PRIVATE KEY-----" > ~/.ssh/id_rsa
        host='nms.radixcloud.com'
        hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
        ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
        cat ~/.ssh/id_rsa
    - run: ssh radix@nms.radixcloud.com 'pwd' 
