on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
         mkdir -p ~/.ssh/
         echo "${{ vars.SSH_KEYS }}" > ~/.ssh/private.key
         sudo chmod 600 ~/.ssh/private.key
         echo "nms.radixcloud.com" > ~/.ssh/known_hosts
      shell: bash
    - name: connect and pull
      run: ssh -i ~/.ssh/private.key radix@nms.radixcloud.com "ls"
    - name: cleanup
      run: rm -rf ~/.ssh
