name: CI

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: Add SSH key
              uses: appleboy/ssh-action@master
              with:
                host: nms.radixcloud.com
                username: radix
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                            ls
 

         
