on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: Create SSH key
        run: |
          sudo apt update -y 
          sudo apt install openssh-client rsync -y
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -t rsa nms.radixcloud.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh radix@nms.radixcloud.com "ls"
      - name: cleanup
        run: rm -rf ~/.ssh
      
