on:
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: donevgoran/ubuntu-cicd
    steps:
      - name: test
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"
