name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          ssh -i ~/.ssh/private.key -o "StrictHostKeyChecking no" radix@nms.radixcloud.com "whoami"
      
      - name: connect and pull
        run: ssh radix@nms.radixcloud.com "touch githubcicd"
      - name: cleanup
        run: rm -rf ~/.ssh
      
