on:
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: donevgoran/ubuntu-cicd
    steps:
    - run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ vars.SSH_HOST }}" > ~/test
        host='nms.radixcloud.com'
        hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
        ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
        cat ~/test
    #- run: ssh radix@nms.radixcloud.com 'pwd' 
