on:
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: donevgoran/ubuntu-cicd
    steps:
    - run: eval $(ssh-agent -s)
    - run: ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
    - run: mkdir -p ~/.ssh
    - run: '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - run: ssh radix@nms.radixcloud.com 'ls'
