on:
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: donevgoran/ubuntu-cicd
    steps:
      - run: echo "var1: ${{ vars.SSH_KEYS }}"
