on:
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: donevgoran/ubuntu-cicd
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DEPLOY_USER_PROD }}
          SSH_KEY: ${{ secrets.DEPLOY_KEY_PROD }}
          SSH_HOST: ${{ secrets.DEPLOY_HOST_PROD }}
      - name: Build and Run App
        run: ssh staging 'pwd'
