on:
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: donevgoran/ubuntu-cicd
    steps:
      - name: test
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: radix
          SSH_KEY: ${{ vars.SSH_KEYS }}
          SSH_HOST: nms.radixcloud.com
      - name:
        run: cat ~/.ssh/staging.key
