on:
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: donevgoran/ubuntu-cicd
    steps:
    - run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        host='nms.radixcloud.com'
        hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
        ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
    - run: ssh radix@nms.radixcloud.com 'pwd' 
